=head1 UPGRADING FROM RT 4.4.0 and greater

This documentation notes internals changes between the 4.4 and 4.6
series that are primarily of interest to developers writing extensions
or local customizations.  It is not an exhaustive list.

=over

=item *

New group options were added to the ticket listings pages in SelfService. With
the additions, the C<AfterMyRequests> callback is no longer at the bottom of the
page. If you previously used this callback to add to the bottom of the SelfService
page, a new callback C<AfterMyGroupRequests> is now available below the new group
ticket listing.

=back

=cut
