# This Dockerfile is for testing only.

FROM bpssysadmin/rt-base-debian:RT-5.0.6-bullseye-testoracle-20240501

ENV RT_TEST_DB_HOST=172.17.0.2
ENV RT_TEST_RT_HOST=172.17.0.3
ENV RT_TEST_DEVEL=1
ENV RT_DBA_USER=system
ENV RT_DBA_PASSWORD=password
ENV RT_TEST_DB_SID=freepdb1
ENV RT_TEST_WEB_HANDLER=inline
ENV RT_TEST_PARALLEL_NUM=2
ENV RT_TEST_PARALLEL=1

# Add the rt_test user (required by mod_fcgid tests)
RUN adduser --disabled-password --gecos "" rt-user

CMD bash -c "ldconfig && cpan -a </dev/null >/dev/null && cat ~/.cpan/Bundle/Snapshot_*.pm && tail -f /dev/null"
