#language: bash
#services: docker

on: push

runs:
  using: "docker"
  image: "Dockerfile"

jobs:
  name: MariaDB and RT web server

  steps:
    - name: Build RT
      uses: actions/checkout@v2
      env:
        RT_TEST_PARALLEL: 1
        RT_DBA_USER: root
        RT_DBA_PASSWORD: password
        DB_VERSION_TAG: 10.3
      shell: bash
      run: |
        docker run --name mariadb -e MYSQL_ROOT_PASSWORD=password -d mariadb:$DB_VERSION_TAG
        docker build -t rt-base .
        docker run -d -v $GITHUB_WORKSPACE:/rt --name rt --link mariadb:db rt-base
        docker ps -a
        docker exec -it rt bash -c "cd /rt && ./configure.ac --with-db-type=mysql --with-my-user-group --enable-layout=inplace --enable-developer --enable-externalauth --enable-gpg --enable-smime && mkdir -p /rt/var && make testdeps"

    - name: Run RT tests
      uses: actions/checkout@v2
      env:
        RT_TEST_PARALLEL: 1
        RT_DBA_USER: root
        RT_DBA_PASSWORD: password
        DB_VERSION_TAG: 10.3
      shell: bash
      run: docker exec -it rt bash -c "cd /rt && prove -lj9 t/*"
