package RT::Config;
# changes: undef => '', array => arrayref, hash => hashref
=head1 NAME

RT::Config

=for testing

use RT::Config;

=cut

=head1 WARNING

NEVER EDIT RT_Config.pm.

Instead, copy any sections you want to change to F<RT_SiteConfig.pm> and edit them there.

=cut

=head1 Base Configuration

=over 4

=item C<rtname>

C<rtname> is the string that RT will look for in mail messages to
figure out what ticket a new piece of mail belongs to.

Your domain name is recommended, so as not to pollute the namespace.
once you start using a given tag, you should probably never change it.
(otherwise, mail for existing tickets won't get put in the right place)

=cut

set(rtname => "example.com");


=item C<email_subject_tag_regex>

This regexp controls what subject tags RT recognizes as its own.
If you're not dealing with historical C<rtname> values, you'll likely
never have to enable this feature.

Be VERY CAREFUL with it. Note that it overrides C<rtname> for subject
token matching and that you should use only "non-capturing" parenthesis
grouping. For example:

C<set(email_subject_tag_regex => qr/(?:example.com|example.org)/i );>

and NOT

C<set(email_subject_tag_regex => qr/(example.com|example.org)/i );>

This setting would make RT behave exactly as it does without the 
setting enabled.

=cut

set( email_subject_tag_regex => '{{rtname}}' );



=item C<organization>

You should set this to your organization's DNS domain. For example,
I<fsck.com> or I<asylum.arkham.ma.us>. It's used by the linking interface to
guarantee that ticket URIs are unique and easy to construct.

=cut

set(organization => "example.com");

=item C<minimum_password_length>

C<minimum_password_length> defines the minimum length for user
passwords. Setting it to 0 disables this check.

=cut

set(minimum_password_length => "5");

=item C<time_zone>

C<time_zone> is used to convert times entered by users into GMT and back again
It should be set to a time zone recognized by L<DateTime::TimeZone>.

=cut

set(time_zone => 'America/New_York');

=back

=head1 Database Configuration

=over 4

=item C<database_type>

Database driver being used; case matters.

Valid types are "mysql", "Oracle" and "Pg"

=cut

set(database_type => 'SQLite');

=item C<database_host>, C<database_rt_host>

The domain name of your database server.

If you're running mysql and it's on localhost,
leave it blank for enhanced performance

=cut

set(database_host => 'localhost');
set(database_rt_host => 'localhost');

=item C<database_port>

The port that your database server is running on.  Ignored unless it's
a positive integer. It's usually safe to leave this blank

=cut

set(database_port => '');

=item C<database_user>

The name of the database user (inside the database)

=cut

set(database_user => 'rt_user');

=item C<database_password>

Password the C<database_user> should use to access the database

=cut

set(database_password => 'rt_pass');

=item C<database_name>

The name of the RT's database on your database server

=cut

set(database_name => 'rt3');

=item C<database_require_ssl>

If you're using Postgres and have compiled in SSL support,
set C<database_require_ssl> to 1 to turn on SSL communication

=cut

set(database_require_ssl => '');

=item C<use_sql_for_acl_checks>

In RT for ages ACL are checked after search what in some situtations
result in empty search pages and wrong count of tickets.

Set C<use_sql_for_acl_checks> to 1 to use SQL and get rid of these problems.

However, this option is beta. In some cases it result in performance
improvements, but some setups can not handle it.

=cut

set(use_sql_for_acl_checks => undef);

=item C<full_text_search>

Full text search (FTS) without indexes is slow operation and by default is
disabled at all. To enable FTS set key 'enabled' to true value.

Setup of indexes and filling them with data requires different steps for
different database back-ends. Use F<sbin/rt-setup-fulltext-index> helper
for quick start. This script creates required structures in the DB and
gives some ideas on next steps.

=cut

set( full_text_search =>
    {
        enable  => 0,
        indexed => 0,

        #    Table   => 'AttachmentsIndex',
        #    Column  => 'ftsindex',
    }
);

=back

=head1 Incoming Mail Gateway Configuration

=over 4

=item C<owner_email>

C<owner_email> is the address of a human who manages RT. RT will send
errors generated by the mail gateway to this address.  This address
should _not_ be an address that's managed by your RT instance.

=cut

set(owner_email => 'root');

=item C<loops_to_rt_owner>

If C<loops_to_rt_owner> is defined, RT will send mail that it believes
might be a loop to C<owner_email>

=cut

set(loops_to_rt_owner => 1);

=item C<store_loops>

If C<store_loops> is defined, RT will record messages that it believes
to be part of mail loops.

As it does this, it will try to be careful not to send mail to the
sender of these messages

=cut

set(store_loops => undef);

=item C<max_attachment_size>

C<max_attachment_size> sets the maximum size (in bytes) of attachments stored
in the database.

For mysql and oracle, we set this size at 10 megabytes.
If you're running a postgres version earlier than 7.1, you will need
to drop this to 8192. (8k)

=cut


set(max_attachment_size => 10000000);

=item C<truncate_long_attachments>

C<truncate_long_attachments>: if this is set to a non-'' value,
RT will truncate attachments longer than C<max_attachment_size>.

=cut

set(truncate_long_attachments => undef);

=item C<drop_long_attachments>

C<drop_long_attachments>: if this is set to a non-'' value,
RT will silently drop attachments longer than C<MaxAttachmentSize>.

=cut

set(drop_long_attachments => undef);

=item C<parse_new_message_for_ticket_ccs>

If C<parse_new_message_for_ticket_ccs> is true, RT will attempt to divine
Ticket 'Cc' watchers from the To and Cc lines of incoming messages
Be forewarned that if you have _any_ addresses which forward mail to
RT automatically and you enable this option without modifying
C<rt_address_regexp> below, you will get yourself into a heap of trouble.

=cut

set(parse_new_message_for_ticket_ccs => undef);

=item C<rt_address_regexp> 

C<rt_address_regexp> is used to make sure RT doesn't add itself as a ticket CC if
the setting above is enabled.

=cut

set(rt_address_regexp => '^rt\@example.com$');

=item C<canonicalize_email_match>, C<canonicalize_email_replace>

RT provides functionality which allows the system to rewrite
incoming email addresses.  In its simplest form,
you can substitute the value in $<CanonicalizeEmailAddressReplace>
for the value in $<CanonicalizeEmailAddressMatch>
(These values are passed to the $<CanonicalizeEmailAddress> subroutine in
 F<RT/User.pm>)

By default, that routine performs a C<s/$match/$replace/gi> on any address
passed to it.

=cut

set(canonicalize_email_match => '');
set(canonicalize_email_replace => '');

=item C<canonicalize_email_match>

Set this to true and the create new user page will use the values that you
enter in the form but use the function CanonicalizeUserInfo in
F<RT/User_Local.pm>

=cut

set(canonicalize_on_create => 0);

=item C<sender_must_exist_in_external_database>

If C<sender_must_exist_in_external_database> is true, RT will refuse to
create non-privileged accounts for unknown users if you are using
the C<lookup_sender_in_external_database> option.
Instead, an error message will be mailed and RT will forward the
message to C<rt_owner>.

If you are not using C<lookup_sender_in_external_database>, this option
has no effect.

If you define an AutoRejectRequest template, RT will use this
template for the rejection message.

=cut

set(sender_must_exist_in_external_database => undef);

=item C<mail_plugins>

C<mail_plugins> is a list of auth plugins for L<RT::Interface::Email>
to use; see L<rt-mailgate>

=cut

set(mail_plugins => []);


=item C<unsafe_email_commands>

C<unsafe_email_commands>, if set to true, enables 'take' and 'resolve'
as possible actions via the mail gateway.  As its name implies, this
is very unsafe, as it allows email with a forged sender to possibly
resolve arbitrary tickets!

=cut

=item C<extract_subject_tag_match>, C<extract_subject_tag_no_match>

The default "extract remote tracking tags" scrip settings; these
detect when your RT is talking to another RT, and adjusts the
subject accordingly.

=cut

set( extract_subject_tag_match => '\\[.+? #\\d+\\]' );
#set( extract_subject_tag_no_match => "\[\Q{{rtname}}\\E #\\d+\\]/" );

=back

=head1 Outgoing Mail Configuration

=over 4

=item C<mail_command>

C<mail_command> defines which method RT will use to try to send mail.
We know that 'sendmailpipe' works fairly well.  If 'sendmailpipe'
doesn't work well for you, try 'sendmail'.  Other options are 'smtp'
or 'qmail'.

Note that you should remove the '-t' from C<sendmail_arguments>
if you use 'sendmail' rather than 'sendmailpipe'

=cut

set(mail_command => 'sendmailpipe');

=back

=head1 Sendmail Configuration

These options only take effect if C<mail_command> is 'sendmail' or
'sendmailpipe'

=over 4

=item C<sendmail_arguments> 

C<sendmail_arguments> defines what flags to pass to C<sendmail_path>
If you picked 'sendmailpipe', you MUST add a -t flag to C<sendmail_arguments>
These options are good for most sendmail wrappers and workalikes

These arguments are good for sendmail brand sendmail 8 and newer
C<set(sendmail_arguments => "-oi -t -ODeliveryMode=b -OErrorMode=m");>

=cut

set(sendmail_arguments => "-oi -t");


=item C<sendmail_bounce_arguments>

C<sendmail_bounce_arguments> defines what flags to pass to C<sendmail>
assuming RT needs to send an error (ie. bounce).

=cut

set(sendmail_bounce_arguments => '-f "<>"');

=item C<sendmail_path>

If you selected 'sendmailpipe' above, you MUST specify the path to
your sendmail binary in C<sendmail_path>.

=cut

set(sendmail_path => "/usr/sbin/sendmail");


=back

=head1 SMTP Configuration

These options only take effect if C<mail_command> is 'smtp'

=over 4

=item C<smtp_server>

C<smtp_server> should be set to the hostname of the SMTP server to use

=cut

set(smtp_server => undef);

=item C<smtp_from>

C<smtp_from> should be set to the 'From' address to use, if not the
email's 'From'

=cut

set(smtp_from => undef);

=item C<smtp_debug> 

C<smtp_debug> should be set to true to debug SMTP mail sending

=cut

set(smtp_debug => 0);

=back

=head1 Other Mailer Configuration

=over 4

=item C<mail_params>

C<mail_params> defines a list of options passed to $mail_command if it
is not 'sendmailpipe', 'sendmail', or 'smtp'

=cut

set(mail_params => []);

=item C<correspond_address>, C<comment_address>

RT is designed such that any mail which already has a ticket-id associated
with it will get to the right place automatically.

C<correspond_address> and C<comment_address> are the default addresses
that will be listed in From: and Reply-To: headers of correspondence
and comment mail tracked by RT, unless overridden by a queue-specific
address.

=cut

set(correspond_address => '');

set(comment_address => '');

=item C<dashboard_address>

The email address from which RT will send dashboards. If none is set, then
C<owneremail> will be used.

=cut

set(dashboard_address => '');


=item C<use_friendly_from_line>

By default, RT sets the outgoing mail's "From:" header to
"SenderName via RT".  Setting C<use_friendly_from_line> to 0 disables it.

=cut

set(use_friendly_from_line => 1);

=item C<friendly_from_line_format>

C<sprintf()> format of the friendly 'From:' header; its arguments
are SenderName and SenderEmailAddress.

=cut

set(friendly_from_line_format => "\"%s via RT\" <%s>");

=item C<use_friendly_to_line>

RT can optionally set a "Friendly" 'To:' header when sending messages to
Ccs or AdminCcs (rather than having a blank 'To:' header.

This feature DOES NOT WORK WITH SENDMAIL[tm] BRAND SENDMAIL
If you are using sendmail, rather than postfix, qmail, exim or some other MTA,
you _must_ disable this option.

=cut

set(use_friendly_to_line => 0);

=item C<friendly_to_line_format>

C<sprintf()> format of the friendly 'From:' header; its arguments
are WatcherType and TicketId.

=cut

set(friendly_to_line_format => "\"%s of {{rtname}} Ticket #%s\":;");

=item C<notify_actor>

By default, RT doesn't notify the person who performs an update, as they
already know what they've done. If you'd like to change this behaviour,
Set C<notify_actor> to 1

=cut

set(notify_actor => 0);

=item C<record_outgoing_email>

By default, RT records each message it sends out to its own internal database.
To change this behavior, set C<record_outgoing_email> to 0 

=cut

set(record_outgoing_email => 1);

=item C<verp_prefix>, C<verp_prefix>

VERP support (http://cr.yp.to/proto/verp.txt)

uncomment the following two directives to generate envelope senders
of the form C<${VERPPrefix}${originaladdress}@${VERPDomain}>
(i.e. rt-jesse=fsck.com@rt.example.com ).

This currently only works with sendmail and sendmailppie.

=cut

# set(verp_prefix => 'rt-');
# set(verp_domain => $rt::organization);


=item C<forward_from_user>

By default, RT forwards a message using queue's address and adds RT's tag into
subject of the outgoing message, so recipients' replies go into RT as correspondents.

To change this behavior, set C<forward_from_user> to true value and RT will use
address of the current user and leave subject without RT's tag.

=cut

set(forward_from_user => 0);

=item C<show_bcc_header>

By default RT hides from the web UI information about blind copies user sent on
reply or comment.

To change this set the following option to true value.

=cut

set(show_bcc_header => 0);

=item C<dashboard_subject>

Lets you set the subject of dashboards. Arguments are the frequency (Daily,
Weekly, Monthly) of the dashboard and the dashboard's name. %1 for the name
of the dashboard.

=cut

set(dashboard_subject => '%s Dashboard: %s');

=back

=head1 GnuPG Configuration

A full description of the (somewhat extensive) GnuPG integration can be found 
by running the command `perldoc L<RT::Crypt::GnuPG>`  (or `perldoc
        lib/RT/Crypt/GnuPG.pm` from your RT install directory).

=over 4

=item C<gnu_pg>

Set C<outgoing_messages_format> to 'inline' to use inline encryption and
signatures instead of 'RFC' (GPG/MIME: RFC3156 and RFC1847) format.

If you want to allow people to encrypt attachments inside the DB then
set C<allow_encrypt_data_in_db> to true

=cut

set( gnupg =>
    {
        enable                   => 1,
        outgoing_messages_format => 'RFC',    # Inline
        allow_encrypt_data_in_db => 0,
    }
);

=item C<gnupg_options>

Options of GnuPG program.

If you override this in your RT_SiteConfig, you should be sure
to include a homedir setting.

NOTE that options with '-' character MUST be quoted.

=cut

set( gnupg_options =>
    {
        # homedir => '/home/jesse/svk/3.999-DANGEROUS/var/data/gpg',

        # URL of a keyserver
        #    keyserver => 'hkp://subkeys.pgp.net',

        # enables the automatic retrieving of keys when encrypting
        #    'auto-key-locate' => 'keyserver',

        # enables the automatic retrieving of keys when verifying signatures
        #    'auto-key-retrieve' => '',
    }
);


=back

=head1 Logging Configuration

The default is to log anything except debugging
information to syslog.  Check the L<Log::Dispatch> POD for
information about how to get things by syslog, mail or anything
else, get debugging info in the log, etc.

It might generally make sense to send error and higher by email to
some administrator.  If you do this, be careful that this email
isn't sent to this RT instance.  Mail loops will generate a critical
log message.

=over 4

=item C<log_to_syslog>, C<log_to_screen>

The minimum level error that will be logged to the specific device.
From lowest to highest priority, the levels are:
 debug info notice warning error critical alert emergency

=cut

set(log_to_syslog => 'info');
set(log_to_screen => 'info');

=item C<log_to_file>, C<log_dir>, C<log_to_file_named>

Logging to a standalone file is also possible, but note that the
file should needs to both exist and be writable by all direct users
of the RT API.  This generally include the web server, whoever
rt-crontool runs as.  Note that as rt-mailgate and the RT CLI go
through the webserver, so their users do not need to have write
permissions to this file. If you expect to have multiple users of
the direct API, Best Practical recommends using syslog instead of
direct file logging.

=cut

set(log_to_file => undef);
set(log_dir => '');
set(log_to_file_named => "rt.log");    #log to rt.log

=item C<log_to_syslog_conf>

On Solaris or UnixWare, set to ( socket => 'inet' ).  Options here
override any other options RT passes to L<Log::Dispatch::Syslog>.
Other interesting flags include facility and logopt.  (See the
L<Log::Dispatch::Syslog> documentation for more information.)  (Maybe
ident too, if you have multiple RT installations.)

=cut

set(log_to_syslog_conf => []);

=item C<statement_log>,

RT has rudimentary SQL statement logging support if you have
DBIx-SearchBuilder 1.31_1 or higher; simply set C<statement_log> to be
the level that you wish SQL statements to be logged at.

=cut

set(statement_log => undef);

=back

=head1 Web Interface Configuration

=over 4

=item C<web_default_stylesheet>

This determines the default stylesheet the RT web interface will use.
RT ships with several themes by default:

  web2            The totally new, default layout for RT 3.8
  3.5-default     RT 3.5 and 3.6 original layout
  3.4-compat      A 3.4 compatibility stylesheet to make RT look
                  (mostly) like 3.4

This value actually specifies a directory in F<share/html/NoAuth/css/>
from which RT will try to load the file main.css (which should
@import any other files the stylesheet needs).  This allows you to
easily and cleanly create your own stylesheets to apply to RT.  This
option can be overridden by users in their preferences.

=cut

set(web_default_stylesheet => 'web2');

=item C<username_format>

This determines how user info is displayed. Concise will show one of 
either NickName, RealName, Name or EmailAddress, depending on what exists 
and whether the user is privileged or not. Verbose will show RealName and
EmailAddress.

=cut

set(username_format => 'concise');


=item C<web_path>

If you're putting the web ui somewhere other than at the root of
your server, you should set C<web_path> to the path you'll be 
serving RT at.

C<web_path> requires a leading / but no trailing /.

In most cases, you should leave C<web_path> set to '' (an empty value).

=cut

set(web_path => "");

=item C<web_port>

If we're running as a superuser, run on port 80
Otherwise, pick a high port for this user.

=cut

set(web_port => 80);# + ($< * 7274) % 32766 + ($< && 1024));

=item C<web_domain>

you know what domain name is, right? ;)

=cut

set(web_domain => 'localhost' );

=item C<web_base_url>, C<web_url>

This is the Scheme, server and port for constructing urls to webrt
C<web_base_url> doesn't need a trailing /

=cut

set(web_base_url => 'http://{{web_domain}}:{{web_port}}');

set(web_url => '{{web_base_url}}{{web_path}}/');

=item C<web_images_url>

C<web_images_url> points to the base URL where RT can find its images.
Define the directory name to be used for images in rt web
documents.

=cut

set(web_images_url => "{{web_path}}/NoAuth/images/");

=item C<logo_url>

C<logo_url> points to the URL of the RT logo displayed in the web UI

=cut

set(logo_url => "{{web_images_url}}bplogo.gif");

=item C<web_no_auth_regex>

What portion of RT's URLspace should not require authentication.

=cut

set(web_no_auth_regex => 
      '(?x-ism:^ (?:\/+NoAuth\/ | \/+REST\/\d+\.\d+\/NoAuth\/) )' );

=item C<self_service_regex>

What portion of RT's URLspace should be accessible to Unprivileged users
This does not override the redirect from F</Ticket/Display.html> to
F</SelfService/Display.html> when Unprivileged users attempt to access
ticked displays

=cut

set(self_service_regex => '^(?:\/+SelfService\/)' );

=item C<message_box_width>, C<message_box_height>

For message boxes, set the entry box width, height and what type of
wrapping to use.  These options can be overridden by users in their
preferences.

Default width: 72, height: 15

These settings only apply to the non-RichText message box.
See below for Rich Text settings.

=cut

set(message_box_width => 72);
set(message_box_height => 15);

=item C<message_box_wrap>

Default wrapping: "HARD"  (choices "SOFT", "HARD")

=cut

set(message_box_wrap => "HARD");

=item C<message_box_rich_text>

Should "rich text" editing be enabled? This option lets your users send html email messages from the web interface.

=cut

set(message_box_rich_text => 1);

=item C<message_box_rich_text_height>

Height of RichText javascript enabled editing boxes (in pixels)

=cut

set(message_box_rich_text_height => 200);

=item C<message_box_include_signature>

Should your user's signatures (from their Preferences page) be included in comments and Replies

=cut

set(message_box_include_signature => 1);

=item C<wiki_implicit_links>

Support implicit links in WikiText custom fields?  A true value
causes InterCapped or ALLCAPS words in WikiText fields to
automatically become links to searches for those words.  If used on
RTFM articles, it links to the RTFM article with that name.

=cut

set(wiki_implicit_links => 0);

=item C<trust_html_attachments>

if C<TrustHTMLAttachments> is not defined, we will display them
as text. This prevents malicious HTML and javascript from being
sent in a request (although there is probably more to it than that)

=cut

set(trust_html_attachments => undef);

=item C<redistribute_auto_generated_messages>

Should RT redistribute correspondence that it identifies as
machine generated? A true value will do so; setting this to '0'
will cause no such messages to be redistributed.
You can also use 'privileged' (the default), which will redistribute
only to privileged users. This helps to protect against malformed
bounces and loops caused by autocreated requestors with bogus addresses.

=cut

set(redistribute_auto_generated_messages => 'privileged');

=item C<prefer_rich_text>

If C<prefer_rich_text> is set to a true value, RT will show HTML/Rich text
messages in preference to their plaintext alternatives. RT "scrubs" the 
html to show only a minimal subset of HTML to avoid possible contamination
by cross-site-scripting attacks.

=cut

set(prefer_rich_text => undef);

=item C<web_external_auth>

If C<web_external_auth> is defined, RT will defer to the environment's
REMOTE_USER variable.

=cut

set(web_external_auth => undef);

=item C<web_fallback_to_internal_auth>

If C<web_fallback_to_internal_auth> is ''ined, the user is allowed a chance
of fallback to the login screen, even if REMOTE_USER failed.

=cut

set(web_fallback_to_internal_auth => undef);

=item C<web_external_gecos>

C<web_external_gecos> means to match 'gecos' field as the user identity);
useful with mod_auth_pwcheck and IIS Integrated Windows logon.

=cut

set(web_external_gecos => undef);

=item C<web_external_auto>

C<web_external_auto> will create users under the same name as REMOTE_USER
upon login, if it's missing in the Users table.

=cut

set(web_external_auto => undef);

=item C<auto_create>

If C<web_external_auto> is true, C<auto_create> will be passed to User's
Create method.  Use it to set defaults, such as creating 
Unprivileged users with C<{ privileged => 0 }>
( Must be a hashref of arguments )

=cut

set(auto_create => undef);

=item C<web_session_class>

C<web_session_class> is the class you wish to use for managing Sessions.
It defaults to use your SQL database, but if you are using MySQL 3.x and
plans to use non-ascii Queue names, uncomment and add this line to
F<RT_SiteConfig.pm> will prevent session corruption.

=cut

# set(web_session_class => 'Apache::Session::File');

=item C<auto_logoff>

By default, RT's user sessions persist until a user closes his or her 
browser. With the C<auto_logoff> option you can setup session lifetime in 
minutes. A user will be logged out if he or she doesn't send any requests 
to RT for the defined time.

=cut

set(auto_logoff => 0);

=item C<web_secure_cookies>

By default, RT's session cookie isn't marked as "secure" Some web browsers 
will treat secure cookies more carefully than non-secure ones, being careful
not to write them to disk, only send them over an SSL secured connection 
and so on. To enable this behaviour, set C<web_secure_cookies> to a true value. 
NOTE: You probably don't want to turn this on _unless_ users are only connecting
via SSL encrypted HTTP connections.

=cut

set(web_secure_cookies => 0);

=item C<web_flush_db_cache_every_request>

By default, RT clears its database cache after every page view.
This ensures that you've always got the most current information 
when working in a multi-process (mod_perl or FastCGI) Environment
Setting C<web_flush_db_cache_every_request> to '0' will turn this off,
which will speed RT up a bit, at the expense of a tiny bit of data 
accuracy.

=cut

set(web_flush_db_cache_every_request => '1');


=item C<max_inline_body>

C<max_inline_body> is the maximum attachment size that we want to see
inline when viewing a transaction.  RT will inline any text if value
is ''ined or 0.  This option can be overridden by users in their
preferences.

=cut

set(max_inline_body => 12000);

=item C<default_summary_rows>

C<default_summary_rows> is default number of rows displayed in for search
results on the frontpage.

=cut

set(default_summary_rows => 10);

=item C<oldest_transactions_first>

By default, RT shows newest transactions at the bottom of the ticket
history page, if you want see them at the top set this to '0'.  This
option can be overridden by users in their preferences.

=cut

set(oldest_transactions_first => '1');

=item C<show_transaction_images>

By default, RT shows images attached to incoming (and outgoing) ticket updates
inline. Set this variable to 0 if you'd like to disable that behaviour

=cut

set(show_transaction_images => 1);

=item C<plain_text_pre>

Normally plaintext attachments are displayed as HTML with line
breaks preserved.  This causes space- and tab-based formatting not
to be displayed correctly.  By setting $plain_text_pre they'll be
displayed using <pre> instead so such formatting works, but they'll
use a monospaced font.

=cut

set(plain_text_pre => 0);


=item C<show_unread_message_notifications>

By default, RT will prompt users when there are new, unread messages on
tickets they are viewing.

Set C<show_unread_message_notifications> to a false value to disable this feature.

=cut

set(show_unread_message_notifications => 1);


=item C<homepage_components>

C<homepage_components> is an arrayref of allowed components on a user's
customized homepage ("RT at a glance").

=cut

set(homepage_components => [qw(QuickCreate QuickSearch MyAdminQueues MySupportQueues MyReminders RefreshHomepage Dashboards)]);


=item C<mason_parameters>

C<mason_parameters> is the list of parameters for the constructor of
HTML::Mason's Apache or CGI Handler.  This is normally only useful
for debugging, eg. profiling individual components with:

    use MasonX::Profiler; # available on CPAN
    set(mason_parameters => [preamble => 'my $p = MasonX::Profiler->new($m, $r);']);

=cut

set(mason_parameters => []);

=item C<default_search_result_format>

C<default_search_result_format> is the default format for RT search results

=cut

set(default_search_result_format => qq{
   '<B><A HREF="__WebPath__/Ticket/Display.html?id=__id__">__id__</a></B>/TITLE:#',
   '<B><A HREF="__WebPath__/Ticket/Display.html?id=__id__">__subject__</a></B>/TITLE:subject',
   status,
   queue_name, 
   owner_name, 
   priority, 
   '__NEWLINE__',
   '', 
   '<small>__requestors__</small>',
   '<small>__created_relative__</small>',
   '<small>__told_relative__</small>',
   '<small>__last_updated_relative__</small>',
   '<small>__time_left__</small>'});


=item C<suppress_inline_text_files>

If C<suppress_inline_text_files> is set to a true value, then uploaded
text files (text-type attachments with file names) are prevented
from being displayed in-line when viewing a ticket's history.

=cut

set(suppress_inline_text_files => undef);

=item C<dont_search_file_attachments>

If C<dont_search_file_attachments> is set to a true value, then uploaded
files (attachments with file names) are not searched during full-content
ticket searches.

=cut

set(dont_search_file_attachments => undef);

=item C<chart_font>

The L<GD> module (which RT uses for graphs) uses a builtin font that doesn't
have full Unicode support. You can use a particular TrueType font by setting
$chart_font to the absolute path of that font. Your GD library must have
support for TrueType fonts to use this option.

=cut

set(chart_font => undef);


=item C<active_make_clicky>

MakeClicky detects various formats of data in headers and email
messages, and extends them with supporting links.  By default, RT
provides two formats:

* 'httpurl': detects http:// and https:// URLs and adds '[Open URL]'
  link after the URL.

* 'httpurl_overwrite': also detects URLs as 'httpurl' format, but
  replace URL with link and *adds spaces* into text if it's longer
  then 30 chars. This allow browser to wrap long URLs and avoid
  horizontal scrolling.

See F<share/html/Elements/MakeClicky> for documentation on how to add your own.

=cut

set(active_make_clicky => []);

=item C<default_queue>

Use this to select the default queue name that will be used for creating new
tickets. You may use either the queue's name or its ID. This only affects the
queue selection boxes on the web interface.

=cut

set(default_queue => 'General');

=back

=head1 L<Net::Server> (rt-server) Configuration

=over 4

=item C<standalone_min_servers>, C<standalone_max_servers>

The absolute minimum and maximum number of servers that will be created to
handle requests. Having multiple servers means that serving a slow page will
affect other users less.

=cut

set(standalone_min_servers => 1);
set(standalone_max_servers => 1);

=item C<standalone_min_spare_servers>, C<standalone_max_spare_servers>

These next two options can be used to scale up and down the number of servers
to adjust to load. These two options will respect the C<$standalone_min_servers
> and C<$standalone_max_servers options>.

=cut

set(standalone_min_spare_servers => 0);
set(standalone_max_spare_servers => 0);

=item C<standalone_max_requests>

This sets the absolute maximum number of requests a single server will serve.
Setting this would be useful if, for example, memory usage slowly crawls up
every hit.

=cut

#set(standalone_max_requests => 50);

=item C<net_server_options>

C<net_server_options> is a hash of additional options to use for
L<Net::Server/DEFAULT ARGUMENTS>. For example, you could set
reverse_lookups to get the hostnames for all users with:

C<set(net_server_options => {reverse_lookups => 1});>

=cut

set(net_server_options => []);

=back


=head1 UTF-8 Configuration

=over 4

=item C<lexicon_languages>

An array that contains languages supported by RT's internationalization
interface.  Defaults to all *.po lexicons; setting it to C<qw(en ja)> will make
RT bilingual instead of multilingual, but will save some memory.

=cut

set(lexicon_languages => [qw(*)]);

=item C<email_input_encodings>

An array that contains default encodings used to guess which charset
an attachment uses if not specified.  Must be recognized by
L<Encode::Guess>.

=cut

set(email_input_encodings => [qw(utf-8 iso-8859-1 us-ascii)]);

=item C<email_output_encoding>

The charset for localized email.  Must be recognized by Encode.

=cut

set(email_output_encoding => 'utf-8');


=back

=head1 Date Handling Configuration

=over 4

=item C<date_time_format>

You can choose date and time format. This takes a L<DateTime/strftime> format
specification. See L<DateTime/strftime_Patterns> for a full list of variables.

This option can be overridden by users in their preferences.

Some examples:

C<set(date_time_format => '%a, %d %b %y %h:%m:%s %z');> # RFC2822
C<set(date_time_format => '%y-%m-%d %h:%m:%s');> # ISO

=cut

set(date_time_format => '%Y-%m-%d %H:%M:%S');

# Next two options are for Time::ParseDate

=item C<date_day_before_month>

Set this to 1 if your local date convention looks like "dd/mm/yy"
instead of "mm/dd/yy".

=cut

set(date_day_before_month => 1);

=item C<ambiguous_day_in_past>, C<ambiguous_day_in_future>

Should an unspecified day or year in a date refer to a future or a
past value? For example, should a date of "Tuesday" default to mean
the date for next Tuesday or last Tuesday? Should the date "March 1"
default to the date for next March or last March?

Set $<AmbiguousDayInPast> for the last date, or $<$ambiguous_day_in_future> for the
next date.

The default is usually good.

=cut

set(ambiguous_day_in_past => 0);
set(ambiguous_day_in_future => 0);

=back

=head1 Miscellaneous Configuration

=over 4

=item C<active_status>, C<inactive_status>

You can define new statuses and even reorder existing statuses here.
WARNING. DO NOT DELETE ANY OF THE DEFAULT STATUSES. If you do, RT
will break horribly. The statuses you add must be no longer than
10 characters.

=cut

set(active_status => [qw(new open stalled)]);
set(inactive_status => [qw(resolved rejected deleted)]);

=item C<link_transactions_run1_scrip>

RT-3.4 backward compatibility setting. Add/Delete Link used to record one
transaction and run one scrip. Set this value to 1 if you want
only one of the link transactions to have scrips run.

=cut

set(link_transactions_run1_scrip => 0);

=item C<strict_link_acl>

When this feature is enabled a user needs I<ModifyTicket> rights on both
tickets to link them together, otherwise he can have rights on either of
them.

=cut

set(strict_link_acl => 1);

=item C<preview_scrip_messages>

Set C<preview_scrip_messages> to 1 if the scrips preview on the ticket
reply page should include the content of the messages to be sent.

=cut

set(preview_scrip_messages => 0);

=item C<use_transaction_batch>

Set C<use_transaction_batch> to 1 to execute transactions in batches,
such that a resolve and comment (for example) would happen
simultaneously, instead of as two transactions, unaware of each
others' existence.

=cut

set(use_transaction_batch => 1);

=item C<custom_field_values_sources>

Set C<custom_field_values_sources> to a list of class names which extend
L<RT::CustomFieldValues::External>.  This can be used to pull lists of
custom field values from external sources at runtime.

=cut

set(custom_field_values_sources => []);

=item C<canonicalize_redirect_urls>

Set C<canonicalize_redirect_urls> to 1 to use $c<WebURL> when redirecting rather
than the one we get from C<env>.

If you use RT behind a reverse proxy, you almost certainly want to
enable this option.

=cut

set(canonicalize_redirect_urls => 0);
=item C<enable_reminders>

Hide links/portlets related to Reminders by setting this to 0

=cut

set(enable_reminders => 1);

=back

=head1 Development Configuration

=over 4

=item C<devel_mode>

RT comes with a "Development mode" setting. 
This setting, as a convenience for developers, turns on 
all sorts of development options that you most likely don't want in 
production:

* Turns off Mason's 'static_source' directive. By default, you can't 
  edit RT's web ui components on the fly and have RT magically pick up
  your changes. (It's a big performance hit)

 * More to come

=cut

set(devel_mode => '1');


=back

=head1 Deprecated Options

=over 4

=item C<always_use_base64>

Encode blobs as base64 in DB (?)

=item C<ticket_base_uri>

Base URI to tickets in this system; used when loading (?)

=item C<use_code_tickets>

This option is exists for backwards compatibility.  Don't use it.

=back

=cut

1;
