Set( $DatabaseUser, 'rt_user' );
Set( $SendmailBounceArguments, '-f "<>"' );
Set( $Timezone, '' );
Set( $CorrespondAddress, 'RT_CorrespondAddressNotSet' );
Set( $rtname, 'example.com' );
Set( $DatabaseRequireSSL, '0' );
Set( $SendmailArguments, '-oi -t' );
Set( $Organization, 'example.com' );
Set( $MaxAttachmentSize, '10000' );
Set( $DatabaseType, 'mysql' );
Set( $DatabasePassword, 'rt_pass' );
Set( $DatabaseAdmin, 'root' );
Set( $SendmailPath, '/usr/sbin/sendmail' );
Set( $MailCommand, 'sendmailpipe' );
Set( $CommentAddress, 'RT_CommentAddressNotSet' );
Set( $DatabaseHost, 'localhost' );
Set( $MinimumPasswordLength, '5' );
Set( $DatabaseName, 'rt3' );
Set( $OwnerEmail, 'root' );
1;
