my $gratuitous = {

'Groups' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'Name', 'varchar', 'NULL', '16', '',
    'Description', 'varchar', 'NULL', '64', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'ACL' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'PrincipalId', 'integer', 'NULL', '', '',
    'PrincipalType', 'varchar', 'NULL', '25', '',
    'RightName', 'varchar', 'NULL', '25', '',
    'RightScope', 'varchar', 'NULL', '25', '',
    'RightAppliesTo', 'integer', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Watchers' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'Type', 'varchar', 'NULL', '16', '',
    'Scope', 'varchar', 'NULL', '16', '',
    'Value', 'integer', 'NULL', '', '',
    'Email', 'varchar', 'NULL', '255', '',
    'Quiet', 'integer', 'NULL', '', '',
    'Owner', 'integer', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Links' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'Base', 'varchar', 'NULL', '255', '',
    'Target', 'varchar', 'NULL', '255', '',
    'Type', 'varchar', '', '20', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Users' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'UserId', 'varchar', '', '120', '',
    'Password', 'varchar', 'NULL', '40', '',
    'Comments', 'blob', 'NULL', '', '',
    'Signature', 'blob', 'NULL', '', '',
    'EmailAddress', 'varchar', 'NULL', '120', '',
    'FreeformContactInfo', 'blob', 'NULL', '', '',
    'Organization', 'varchar', 'NULL', '200', '',
    'Disabled', 'integer', 'NULL', '', '',
    'CanManipulate', 'integer', 'NULL', '', '',
    'RealName', 'varchar', 'NULL', '120', '',
    'Nickname', 'varchar', 'NULL', '16', '',
    'Lang', 'varchar', 'NULL', '16', '',
    'EmailEncoding', 'varchar', 'NULL', '16', '',
    'WebEncoding', 'varchar', 'NULL', '16', '',
    'ExternalContactInfoId', 'varchar', 'NULL', '100', '',
    'ContactInfoSystem', 'varchar', 'NULL', '30', '',
    'ExternalAuthId', 'varchar', 'NULL', '100', '',
    'AuthSystem', 'varchar', 'NULL', '30', '',
    'Gecos', 'varchar', 'NULL', '16', '',
    'HomePhone', 'varchar', 'NULL', '30', '',
    'WorkPhone', 'varchar', 'NULL', '30', '',
    'MobilePhone', 'varchar', 'NULL', '30', '',
    'PagerPhone', 'varchar', 'NULL', '30', '',
    'Address1', 'varchar', 'NULL', '200', '',
    'Address2', 'varchar', 'NULL', '200', '',
    'City', 'varchar', 'NULL', '100', '',
    'State', 'varchar', 'NULL', '100', '',
    'Zip', 'varchar', 'NULL', '16', '',
    'Country', 'varchar', 'NULL', '50', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Scrips' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'Name', 'varchar', 'NULL', '255', '',
    'Description', 'varchar', 'NULL', '255', '',
    'Type', 'varchar', 'NULL', '60', '',
    'ExecModulE', 'varchar', 'NULL', '60', '',
    'DefaultTemplate', 'integer', 'NULL', '', '',
    'Argument', 'varchar', 'NULL', '255', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Tickets' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'EffectiveId', 'integer', 'NULL', '', '',
    'Queue', 'integer', 'NULL', '', '',
    'Alias', 'varchar', 'NULL', '40', '',
    'Type', 'varchar', 'NULL', '16', '',
    'IssueStatement', 'integer', 'NULL', '', '',
    'Resolution', 'integer', 'NULL', '', '',
    'Owner', 'integer', 'NULL', '', '',
    'Subject', 'varchar', 'NULL', '200', '',
    'InitialPriority', 'integer', 'NULL', '', '',
    'FinalPriority', 'integer', 'NULL', '', '',
    'Priority', 'integer', 'NULL', '', '',
    'Status', 'varchar', 'NULL', '10', '',
    'TimeWorked', 'integer', 'NULL', '', '',
    'TimeLeft', 'integer', 'NULL', '', '',
    'Told', 'timestamp', 'NULL', '', '',
    'Starts', 'timestamp', 'NULL', '', '',
    'Started', 'timestamp', 'NULL', '', '',
    'Due', 'timestamp', 'NULL', '', '',
    'Resolved', 'timestamp', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'GroupMembers' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'GroupId', 'integer', 'NULL', '', '',
    'UserId', 'integer', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Queues' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'QueueId', 'varchar', '', '40', '',
    'Description', 'varchar', 'NULL', '120', '',
    'CorrespondAddress', 'varchar', 'NULL', '40', '',
    'CommentAddress', 'varchar', 'NULL', '40', '',
    'InitialPriority', 'integer', 'NULL', '', '',
    'FinalPriority', 'integer', 'NULL', '', '',
    'DefaultDueIn', 'integer', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Transactions' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'EffectiveTicket', 'integer', 'NULL', '', '',
    'Ticket', 'integer', 'NULL', '', '',
    'TimeTaken', 'integer', 'NULL', '', '',
    'Type', 'varchar', 'NULL', '20', '',
    'Field', 'varchar', 'NULL', '40', '',
    'OldValue', 'varchar', 'NULL', '255', '',
    'NewValue', 'varchar', 'NULL', '255', '',
    'Data', 'varchar', 'NULL', '100', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'ScripScope' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'Scrip', 'integer', 'NULL', '', '',
    'Queue', 'integer', 'NULL', '', '',
    'Template', 'integer', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Attachments' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'TransactionId', 'integer', '', '', '',
    'Parent', 'integer', 'NULL', '', '',
    'MessageId', 'varchar', 'NULL', '160', '',
    'Subject', 'varchar', 'NULL', '255', '',
    'Filename', 'varchar', 'NULL', '255', '',
    'ContentType', 'varchar', 'NULL', '80', '',
    'Content', 'blob', 'NULL', '', '',
    'Headers', 'blob', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
},

'Templates' => {
  'columns' => [
    'id', 'integer', '', '', 'AUTO_INCREMENT',
    'Title', 'varchar', 'NULL', '120', '',
    'Language', 'varchar', 'NULL', '16', '',
    'TranslationOf', 'integer', 'NULL', '', '',
    'Content', 'blob', 'NULL', '', '',
    'LastUpdatedBy', 'integer', 'NULL', '', '',
    'LastUpdated', 'timestamp', 'NULL', '', '',
    'Creator', 'integer', 'NULL', '', '',
    'Created', 'timestamp', 'NULL', '', '',
  ],
  'primary_key' => 'id',
  'unique' => [  ],
  'index' => [  ],
}

};
