#!/usr/bin/perl -w

# $Header: /raid/cvsroot/rt/sbin/Attic/testdeps,v 1.1.2.1 2002/01/28 05:27:15 jesse Exp $

# Copyright 2000 Jesse Vincent <jesse@fsck.com>
# Distributed under the GNU General Public License
# 

#
# This is just a basic script that checks to make sure that all
# the modules needed by RT before you can install it.
#

use strict;

use vars qw($mode $dbd @modules);

$mode = shift || print_help();
$dbd = shift || print_help();

my @core_modules = qw(
CPAN 1.60
DBI 1.18
Test::Inline
Class::ReturnValue 0.21
DBIx::SearchBuilder 0.62
DBIx::DataSource 0.02
Text::Template
File::Spec 0.8
HTML::Entities 
Net::Domain
Log::Dispatch 1.6
Locale::Maketext
Locale::Maketext::Lexicon
MIME::Entity 5.108
Mail::Mailer 1.20
Net::SMTP
Text::Wrapper 
Date::Parse
Date::Format 
File::Temp 
);
my @mason_modules = qw(
Params::Validate 0.02
Cache::Cache
Exception::Class
HTML::Mason 1.10
MLDBM
Errno
FreezeThaw
Digest::MD5
CGI::Cookie 1.20
Storable
Apache::Session 1.53);

my @cli_modules = qw(
Getopt::Long 2.24
);

my @dev_modules = qw(
Regexp::Common
Time::HiRes 
Test::Inline 
);

my @fcgi_modules = qw(
FCGI
CGI::Fast 
);

my @modperl_modules = qw( 
Apache::Request 
);

my @db_modules;

if ($dbd =~ /mysql/i) {
        @db_modules = qw(DBD::mysql 2.0416
        );
}
elsif ($dbd =~ /oracle/i) {
        @db_modules = qw(DBD::Oracle
        );
}
elsif ($dbd =~ /pg/i) {
        @db_modules = qw(DBD::Pg
        );
}


@modules =  (@core_modules, @mason_modules, @cli_modules, @dev_modules, @db_modules, @fcgi_modules, @modperl_modules);

use CPAN;

while (my $module= shift @modules) {
	my $version = "";
        next unless ($module);
	$version = " ". shift (@modules) . " " if (@modules && $modules[0] =~ /^([\d\.]*)$/);
	print "Checking for $module$version";
	eval "use $module$version" ;
	if ($@) {
	&resolve_dependency($module, $version) 
	}
	else {
	print "...found\n";
	}
}

sub print_help {
print <<EOF;

$0 FLAG DBTYPE


$0 is a tool for RT that will tell you if you've got all
the modules RT depends on properly installed.

Flags: (only one flag is valid for a given run)

-quiet will check to see if we've got everything we need
	and will exit with a return code of (1) if we don't.

-warn will tell you what isn't properly installed

-fix will use CPAN to magically make everything better

DBTYPE is one of:
	oracle, pg, mysql

EOF

exit(0);
}

sub resolve_dependency {
	my $module = shift;
	my $version = shift;
        print "....$module$version not installed.";
    if ($mode =~ /-f/) {
	$module = "DBD::mysql::Install" if ($module =~ /DBD::mysql/);
	
        print "Installing with CPAN...";
        CPAN::install($module);
     }
     print "\n";
	exit(1) if ($mode =~ /-q/);
}	
	
