# $Header$
# Autogenerated by DBIx::SearchBuilder factory  (by <jesse@fsck.com>)

=head1 NAME

RT::FM::Article

=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 METHODS

=cut

package RT::FM::Article;
use RT::FM::Record; 
use RT::FM::Content;
use RT::FM::User;

use vars qw( @ISA );
@ISA= qw( RT::FM::Record );

sub _Init {
  my $self = shift; 

  $self->Table('Article');
  $self->SUPER::_Init(@_);
}

# {{{ Create


=item Create PARAMHASH

Create takes a hash of values and creates a row in the database:

  int(11) 'id'.
  varchar(200) 'Name'.
  varchar(200) 'Summary'.
  int(11) 'Content'.
  int(11) 'Parent'.
  int(11) 'SortOrder'.
  int(11) 'CreatedBy'.
  datetime 'Created'.
  int(11) 'UpdatedBy'.
  datetime 'Updated'.
  smallint(6) 'Disabled'.

=cut




sub Create {
    my $self = shift;
    my %args = ( 
                id => undef,
                Name => undef,
                Summary => undef,
                Content => undef,
		Parent => 0,
                SortOrder => undef,
                CreatedBy => undef,
                Created => undef,
                UpdatedBy => undef,
                Updated => undef,
                Disabled => 0,
,
		  @_);

    # TODO, check for actual parent object and make sure
    # we're not creating some sort of circular incestuous 
    # relationship

    my $ContentObj = new RT::FM::Content($self->CurrentUser);
    my ($value) = $ContentObj->Create ( Subject => $args{'Summary'},
					ContentType => 'application/x-rtfm-content',
					Body => $args{'Content'} );
    unless ($value) {
	return (0, "Couldn't create new Content blob");
    }

    $self->SUPER::Create(
                         id => $args{'id'},
                         Name => $args{'Name'},
                         Summary => $args{'Summary'},
                         Content => $value,
                         Parent => $args{'Parent'},
                         SortOrder => $args{'SortOrder'},
                         CreatedBy => $args{'CreatedBy'},
                         Created => $args{'Created'},
                         UpdatedBy => $args{'UpdatedBy'},
                         Updated => $args{'Updated'},
                         Disabled => $args{'Disabled'},
			);

}

# }}}

# {{{ Id

=item id

Returns the current value of id. 
(In the database, id is stored as int(11).)


=item Setid VALUE

Set id to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, id will be stored as a int(11).)

=cut

# }}}

# {{{ Name

=item Name

Returns the current value of Name. 
(In the database, Name is stored as varchar(200).)


=item SetName VALUE

Set Name to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Name will be stored as a varchar(200).)

=cut

# }}} 

# {{{ Summary
=item Summary

Returns the current value of Summary. 
(In the database, Summary is stored as varchar(200).)


=item SetSummary VALUE

Set Summary to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Summary will be stored as a varchar(200).)

=cut

# }}}

# {{{ Content

=item Content

Returns the current value of Content. 
(In the database, Content is stored as int(11).)


=item SetContent VALUE

Set Content to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Content will be stored as a int(11).)

=cut

sub SetContent {
    my $self = shift;
    my $new_value = shift;
    my $content = new RT::FM::Content($self->CurrentUser);
    my ($value) = $content->Create ( Subject => $self->Summary(),
				     ContentType => 'application/x-rtfm-content',
				     Body => $new_value );
    unless ($value) {
	return (0, "Couldn't create new Content blob");
    }
    
    
    $self->SUPER::SetContent($value);
}	

    

=item ContentObj

Returns the Content Object which has the id returned by Content


=cut

sub ContentObj {
	my $self = shift;
	my $Content = new RT::FM::Content($self->CurrentUser);
	$Content->Load($self->Content());
	return($Content);
}


# }}}

# {{{ Parent

=item Parent

Returns the current value of Parent. 
(In the database, Parent is stored as int(11).)


=item SetParent VALUE

Set Parent to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Parent will be stored as a int(11).)

=cut


=item ParentObj

Returns the Parent Object which has the id returned by Parent


=cut

sub ParentObj {
	my $self = shift;
	my $Parent = new RT::FM::Article($self->CurrentUser);
	$Parent->Load($self->Parent());
	return($Parent);
}

# }}}

# {{{ Children

=item Children

Returns an RT::FM::ArticleCollection object which contains
all articles which have this article as their parent.  This 
routine will not recurse and will not find grandchildren, great-grandchildren, uncles, aunts, nephews or any other such thing.  

=cut

sub Children {
    my $self = shift;
    my $kids = new RT::FM::ArticleCollection($self->CurrentUser);
    $kids->LimitToParent($self->Id);
    return($kids);
}

# }}}


=item Values CUSTOMFIELDID

Returns an RT::FM::CustomFieldObjectValueCollection object containing
the values of CustomField CUSTOMFIELDID for this Article


=cut
sub Values {
	my $self = shift;
	my $customfield = shift;

	my $cfovc = new RT::FM::CustomFieldObjectValueCollection($self->CurrentUser);
	$cfovc->LimitToArticle($self->Id);
	$cfovc->LimitToCustomField($customfield);
	return ($cfovc);
}

# {{{ SortOrder
=item SortOrder

Returns the current value of SortOrder. 
(In the database, SortOrder is stored as int(11).)


=item SetSortOrder VALUE

Set SortOrder to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, SortOrder will be stored as a int(11).)

=cut

# }}}

# {{{ Creation metadata

=item CreatedBy

Returns the current value of CreatedBy. 
(In the database, CreatedBy is stored as int(11).)


=item SetCreatedBy VALUE

Set CreatedBy to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, CreatedBy will be stored as a int(11).)

=cut


=item CreatedByObj

Returns the User Object which has the id returned by CreatedBy


=cut

sub CreatedByObj {
	my $self = shift;
	my $CreatedBy = new RT::FM::User($self->CurrentUser);
	$CreatedBy->Load($self->CreatedBy());
	return($CreatedBy);
}

=item Created

Returns the current value of Created. 
(In the database, Created is stored as datetime.)


=item SetCreated VALUE

Set Created to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Created will be stored as a datetime.)

=cut

# }}}

# {{{ Update metadata

=item UpdatedBy

Returns the current value of UpdatedBy. 
(In the database, UpdatedBy is stored as int(11).)


=item SetUpdatedBy VALUE

Set UpdatedBy to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, UpdatedBy will be stored as a int(11).)

=cut


=item UpdatedByObj

Returns the User Object which has the id returned by UpdatedBy


=cut

sub UpdatedByObj {
	my $self = shift;
	my $UpdatedBy = new RT::FM::User($self->CurrentUser);
	$UpdatedBy->Load($self->UpdatedBy());
	return($UpdatedBy);
}

=item Updated

Returns the current value of Updated. 
(In the database, Updated is stored as datetime.)


=item SetUpdated VALUE

Set Updated to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Updated will be stored as a datetime.)

=cut

# }}}

# {{{ disabled. will we use this?
=item Disabled

Returns the current value of Disabled. 
(In the database, Disabled is stored as smallint(6).)


=item SetDisabled VALUE

Set Disabled to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Disabled will be stored as a smallint(6).)

=cut

# }}}

# {{{ _ClassAccessible

sub _ClassAccessible {
    {
     
        id => {'read' => 1, 'write' => 1},
        Name => {'read' => 1, 'write' => 1},
        Summary => {'read' => 1, 'write' => 1},
        Content => {'read' => 1, 'write' => 1},
        Parent => {'read' => 1, 'write' => 1},
        SortOrder => {'read' => 1, 'write' => 1},
        CreatedBy => {'read' => 1, 'write' => 1, 'auto' => 1},
        Created => {'read' => 1, 'write' => 1, 'auto' => 1},
        UpdatedBy => {'read' => 1, 'write' => 1, 'auto' => 1},
        Updated => {'read' => 1, 'write' => 1, 'auto' => 1},
        Disabled => {'read' => 1, 'write' => 1},

 }
};

# }}}

1;
