=head1 RTFM's config options

=head2 RTFM_ParseContentAsTemplate (boolean, false)

If true then RTFM parses content of articles as a template
using L<Text::Template> module. Using this option you can
make your articles dynamic. Text::Template module is used
to parse RT's Templates as well and its syntax is pretty
simple - you consult RT docs/wiki or module's documentation.

To enable option add the following line to the site config:

    Set($RTFM_ParseContentAsTemplate, 1);

=cut
