

# $Header$
# Autogenerated by DBIx::SearchBuilder factory  (by <jesse@fsck.com>)

=head1 NAME

  RT::FM::CustomFieldValueCollection -- Class Description
 
=head1 SYNOPSIS

  use RT::FM::CustomFieldValueCollection

=head1 DESCRIPTION


=head1 METHODS

=cut

package RT::FM::CustomFieldValueCollection;

use RT::FM::SearchBuilder;
use RT::FM::CustomFieldValue;

@ISA= qw(RT::FM::SearchBuilder);


sub _Init {
    my $self = shift;
    $self->{'table'} = 'CustomFieldValues';
    $self->{'primary_key'} = 'id';
    return ( $self->SUPER::_Init(@_) );
}


=item NewItem

Returns an empty new RT::FM::CustomFieldValue item

=cut

sub NewItem {
    my $self = shift;
    return(new RT::FM::CustomFieldValue(@_));
}

1;
