

# $Header$
# Autogenerated by DBIx::SearchBuilder factory  (by <jesse@fsck.com>)

=head1 NAME

  RT::FM::TransactionCollection -- Class Description
 
=head1 SYNOPSIS

  use RT::FM::TransactionCollection

=head1 DESCRIPTION


=head1 METHODS

=cut

package RT::FM::TransactionCollection;

use RT::FM::SearchBuilder;
use RT::FM::Transaction;

@ISA= qw(RT::FM::SearchBuilder);


sub _Init {
    my $self = shift;
    $self->{'table'} = 'Transaction';
    $self->{'primary_key'} = 'id';
    return ( $self->SUPER::_Init(@_) );
}


=item NewItem

Returns an empty new RT::FM::Transaction item

=cut

sub NewItem {
    my $self = shift;
    return(new RT::FM::Transaction(@_));
}

1;
