=head1 INTRODUCTION

This text is about 'Subject Tag' property of a queue. This
property allows you to use different tags in subjects of
RT's notifications, by default it's rtname option from
the config file as it's been for a long time, now you can
use different values for different queues.

=head1 CONFIGURATION

Open RT's web UI, goto -E<gt> Configuration -E<gt> Queues
-E<gt> select a queue -E<gt> set 'subject tag' -E<gt>
save changes.

=head1 This functionality vs. RT-Extension-BrandedQueues

RT-Extension-BrandedQueues is extension that's available from
the CPAN for older versions of RT. Starting from RT 3.8 it's
been integrated into RT core. If you are B<UPGRADING> from
older version and were using extension from the CPAN then you
MUST read L</UPGRADING> below.

=head1 UPGRADING

=head2 For everyone who is upgrading

You need to modify any of your email templates which use
the $rtname variable. To edit your templates, log into RT
as your administrative user, then click:

Configuration -> Global -> Templates -> <Some template name>

For example, RT's default "Autoreply" includes this line:

 "There is no need to reply to this message right now.  Your ticket has been
 assigned an ID of [{$rtname} #{$Ticket->id()}]."

Change this line to read:

 "There is no need to reply to this message right now.  Your ticket has been
 assigned an ID of [{ $Ticket->QueueObj->SubjectTag || $rtname } #{$Ticket->id()}]."

=head2 For users of RT-Extension-BrandedQueues

1) You MUST uninstall RT-Extension-BrandedQueues before upgrade
or use clean new dir for installation and reinstall your local
customizations. The latter way is recommended as there are many
changes in RT 3.8 and several extensions have been integrated
into core.

2) We expect that you have backup of your RT DB around during upgrade.

3) After upgrade run perl script 'etc/upgrade/3.8-branded-queues-extension'.
This extension will convert data in the DB into new format.

=cut
