#!/usr/bin/perl

use strict;
use warnings;

die "No \$RT_MAILLOGFILE set in environment"
    unless $ENV{RT_MAILLOGFILE};
open my $log, ">", $ENV{RT_MAILLOGFILE}
    or die "Can't write to $ENV{RT_MAILLOGFILE}: $!";

my $needs_newline;
for (@ARGV) {
    if (/^-/) {
        print $log "\n" if $needs_newline++;
        print $log $_;
    } else {
        print $log " $_";
    }
}
print $log "\n";

1 while $_ = <STDIN>;

exit 0;
