=head1 Templates

Each template is split into two sections. A block of headers and a body. These
sections are separated by a blank line.

=head2 Headers

Your template may specify arbitrary email headers. Each header is a name, a
colon, then a value. So, for example, to specify a subject, you can use:

    Subject: Thanks for your bug report.

=head3 Special Headers

=over

=item Content-Type: text/html

The special header "Content-Type: text/html" tells RT that the template should
be parsed as HTML. RT will automatically make the outgoing message multipart.
That way, recipients who can read only plaintext email will receive something
readable, while users with clients which can display HTML will receive the full
experience. Please be aware that HTML support in mail clients varies greatly,
much more so than different web browsers.

We welcome contributions of HTML-ization of builtin templates.

=back

=head2 Variables

The variables that your templates may use include:

=over 4

=item C<$Transaction>

The transaction object.

=item C<$rtname>

The value of the "rtname" config variable.

=item C<$Ticket>

The ticket object. This is only set during a ticket transaction.

=item C<$Requestor>

This is not an object, but the name of the first requestor on the ticket.
If this is not what you need, inspect C<< $Ticket->Requestors >>.

=item C<loc("text")>

A localization function. See L<Locale::Maketext>.

=back

=cut

