=head1 UPGRADING FROM RT 4.2.0 and greater

The 4.4 release is a major upgrade and as such there are more changes
than in a minor bugfix release (e.g., 4.2.2 to 4.2.3) and some of these
changes are backward-incompatible. The following lists some of the notable
changes, especially those that might require you to change a configuration
option or other setting due to a change in RT. Read this section carefully
before you upgrade and look for changes to features you currently use.

=over

=item *

The support for C<jsmin> (via the C<$JSMinPath> configuration) has been
removed in favor of a built-in solution.

=item *

You can now split settings from F<RT_SiteConfig.pm> into separate files under
an F<etc/RT_SiteConfig.d/> directory. All files ending in C<.pm> will be
parsed, in alphabetical order, after the main F<RT_SiteConfig.pm> is loaded.

=item *

When creating linked tickets from the Links box, Time Worked, Time
Estimated, and Time Left will no longer be copied.  This simplifies time
reporting.

=item *

Custom fields with categories will be split out into hierarchical custom
fields.

=item *

Homepage component "Quicksearch" has been renamed to "QueueList" to reflect
what it actually is. Please update C<$HomepageComponents> accordingly if you
customized it in site config.

=item *

SLA is in core now, so C<SLA> became a core field. if you installed
C<RT::Extension::SLA> before, you need to remove it from your plugins, adjust
configs accordingly and run F<etc/upgrade/upgrade-sla>. see also the SLA
section in F<RT_Config.pm>.

Note that with core SLA, you can't define different set of levels for
different queues. i.e. all the queues share the same set of levels defined in
C<%ServiceAgreements>.

=item *

RT::Interface::Email no longer exports functions.

=item *

Incoming email now always creates users for the C<From:> address.
Previously, if the C<CreateTicket> right was not granted to C<Everyone>
or C<Unprivileged>, the email would be rejected without a user; now, the
user to be created even when the mail is rejected.

=item *

The L<RT_Config/@MailPlugins> functionality has been rewritten; mail
plugins written for previous versions of RT will not function as
expected.  See F<docs/extending/mail_plugins.pod>

=item *

The C<$UnsafeEmailCommands> option has been replaced with two mail
plugins, L<RT::Interface::Email::Action::Take>, and
L<RT::Interface::Email::Action::Resolve>.

=item *

The C<RejectOnUnencrypted> option to L<RT_Config/%Crypt> has been
replaced with a mail plugin,
L<RT::Interface::Email::Authz::RequireEncrypted>.

=back

=cut
