=head1 UPGRADING FROM 3.6.0 AND EARLIER

As there are a large number of code changes, it is highly recommended that you
install RT into a fresh directory, and then reinstall your customizations.

The database schema has changed significantly for mysql 4.1 and above; please
read UPGRADING.mysql for more details.

The configuration format has been made stricter. All options MUST be set using
the Set function; the historical "@XXX = (...) unless @XXX;" is no longer
allowed.

The RTx::Shredder extension has been integrated into core, and several
features have been added, so you MUST uninstall it before upgrading.

A new interface for making links in text clickable, and doing other arbitrary
text replacements, has been integrated into RT.  You can read more in `perldoc
docs/extending/clickable_links.pod`.

A new feature has been added that allows users to forward messages. There is a
new option in the config ($ForwardFromUser), new rights, and a new template.

New global templates have been added with "Error: " prefixed to the name to
make it possible to configure error messages sent to users.

You can read about the new GnuPG integration in `perldoc
lib/RT/Crypt/GnuPG.pm`.

New scrip conditions 'On Close' and 'On Reopen' have been added.


=head1 UPGRADING FROM 3.5.7 AND EARLIER

Scrips are now prepared and committed in order alphanumerically by
description.  This means that you can prepend a number (00, 07, 15, 24) to the
beginning of each scrip's description, and they will run in that order.
Depending on your database, the old ordering may have been by scrip id number
-- if that is the case, simply prepend the scrip id number to the beginning of
its description.


=head1 UPGRADING FROM 3.5.1 AND EARLIER

The default for $RedistributeAutoGeneratedMessages has changed to
'privileged', to make out-of-the-box installations more resistant to
mail loops. If you rely on the old default of redistributing to all watchers,
you'll need to set it explicitly now.
